### ISSUE TITLE
OCR JSON to MS Word Document

### ISSUE THREAD

**Issue by amehmood-pls** [googleapis/python-documentai-toolbox#158]
Hello, I'm uncertain if this is the appropriate repository to pose this question. I've been engaged in experimentation using the DocumentAI which provides JSON output. Additionally, I used the `python-documentai-toolbox` to export the hOCR file. This has led me to wonder whether there exists a readily available module or API designed to transform OCR JSON into a Word document? Thank you!

**Comment by holtskinner** [comment]
Looks like you shouldn't need a special tool to open hOCR in Microsoft Word.

https://groups.google.com/g/tesseract-ocr/c/tEsQFxct2DI

And here's a related doc for how to open an HTML file in Word.

https://smallbusiness.chron.com/edit-html-word-54837.html
