### ISSUE TITLE
Sorting function doesn't need int() conversion

### ISSUE THREAD

**Issue by lababidi** [googleapis/python-documentai-toolbox#199]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-documentai-toolbox/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-documentai-toolbox` version: `pip show google-cloud-documentai-toolbox`

#### Steps to reproduce

  1. ?
  2. ?

#### Code example

```python
wrapped_document = document.Document.from_gcs(
    gcs_bucket_name=gcs_bucket_name, gcs_prefix=gcs_prefix
)
```

#### Stack trace
```
File ~/miniconda/lib/python3.10/site-packages/google/cloud/documentai_toolbox/wrappers/document.py:70, in _entities_from_shards.<locals>.<lambda>(x)
     67     page_offset += len(shard.pages)
     69 if len(result) > 1 and result[0].documentai_object.id:
---> 70     result.sort(key=lambda x: int(x.documentai_object.id))
     71 return result

ValueError: invalid literal for int() with base 10: 'e6a445871928ed89'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by holtskinner** [comment]
Actually, on second thought, the `int` conversion should actually be used for `_entities_from_shards()` because the `entity.id` field is a string in the Document object, and these need to be sorted in numerical order.

Can you upload a sample `Document` json file that causes this issue? (With any PII removed)

Are these Documents imported from a 3rd party service and converted into the Document AI format?

**Comment by lababidi** [comment]
I can't upload the doc as they are very sensitive. They are uploaded into GCS and then imported in to generate the training set in the UI of DocAI

**Comment by holtskinner** [comment]
Ok, what is the source of the Documents? Are they output from Document AI, HITL, Warehouse, something related? Or are they created from a different service?

**Comment by holtskinner** [comment]
Ok, that's very interesting. So those IDs are the result of auto-labeling with Document AI Workbench. I think it could make sense to either:

1. Only perform sorting if the IDs are numeric
2. Remove sorting altogether (Most of the time, I don't think it will be necessary)

**Comment by lababidi** [comment]
Very cool! Thanks!
