### ISSUE TITLE
conversion to HOCR does not convert HTML special characters, it leaves them plain text 

### ISSUE THREAD

**Issue by ThreeHAN** [googleapis/python-documentai-toolbox#213]
#### Issue
When trying to use the output from `export_hocr_str` in xml etree, it fails to parse due to specific HTML special characters (< and &, and probably others). I've included an example file that breaks xml etree parser. I think this can be fixed by updating the template file to use the j2 built in  `escape` to encode html special characters `{{ line.text|escape }}` and `{{ token.text|escape }}`. 

I've included the j2 template that fixes the issue (had to rename file to just text to upload)

[j2 reference (`HTML Escaping` section)](https://jinja.palletsprojects.com/en/3.0.x/templates/ )

[fix for hocr_document_template.xml.j2](https://github.com/googleapis/python-documentai-toolbox/files/13562745/hocr_document_template.xml.j2.txt)

[file that cause issue html-special-characters.pdf](https://github.com/googleapis/python-documentai-toolbox/files/13562732/html-special-characters.pdf)

#### Environment details

  - OS type and version: Windows Server 2019
  - Python version:Python 3.9.4
  - pip version: pip 20.2.3
  - `google-cloud-documentai-toolbox` version:  0.12.0-alpha

#### Steps to reproduce

  1. Create a pdf that has specific special characters embedded in it (&, <, probably others). 
  2. OCR that document with Document AI
  3. Bring that document into the toolkit 
      `document.Document.from_gcs(gcs_bucket_name=BUCKET, gcs_prefix=PREFIX)`
  4. Use the python document ai tool kit to create a hocr file 
      `export_hocr_str(title='Special Characters')` 
  5. This part is successful, but now < & are still clear text in the document
  6. Attempt to import with xml etree parser
  8. Receive invalid token error
      `ParseError: not well-formed (invalid token): line 14, column 293`

#### Code example
Code to OCR the pdf is not included here

```python
    import xml.etree.ElementTree as ET
    from google.cloud.documentai_toolbox import document

    wrapped_document = document.Document.from_gcs(gcs_bucket_name=BUCKET, gcs_prefix=PREFIX)
    hocr_output = wrapped_document.export_hocr_str(title = "Unparseable Doc")
    tree = ET.ElementTree(ET.fromstring(hocr_output))
```

#### Stack trace
```
  File annotatepdf.py:199 in error_validation
    tree = ET.ElementTree(ET.fromstring(hocr_output))

  File c:\Program Files\Python39\lib\xml\etree\ElementTree.py:1347 in XML
    parser.feed(text)

  File 
ParseError: not well-formed (invalid token): line 14, column 293
```

**Comment by ThreeHAN** [comment]
Here is the hocr file outputted by the toolbox to save you a step
[hocr.html.txt](https://github.com/googleapis/python-documentai-toolbox/files/13564742/hocr.html.txt)

**Comment by holtskinner** [comment]
Makes sense, thanks for the catch! Please make a Pull Request for your changes, and also add  unit tests for this edge case.

**Comment by holtskinner** [comment]
I created #239 for you to pull in these changes.
